website/views.py
# This file is for arranging which pages the user can navigate to (i.e. launchpads, launches, rockets, ships...) #
# This file is a blueprint, it has a bunch of roots and urls inside of it #

from flask import Blueprint, render_template, current_app, request, redirect, url_for, flash
from flask_login import current_user, login_user, logout_user, login_required

import passlib.hash

import forms
import database
import users

views = Blueprint('views', __name__)

@views.route("/signup", methods=["GET", "POST"])
def signup():
    form = forms.SignupForm()
    if form.validate_on_submit():
        username = form.data["username"]
        user = users.get_user(username)

        if user is None:
            password = form.data["password"]
            hashed_password = \
                passlib.hash.pbkdf2_sha256.hash(password)

            user_type = "regular"
            deserves_adminhood = True if form.data["superfan"] == "True" else False
            if deserves_adminhood and "wants_admin" in request.form.keys():
                user_type = "admin"

            users.add_user(username, hashed_password, user_type)

            flash("You're all set, you can log in.")
            return redirect(url_for("views.login"))
        else:
            flash("That username is taken, please choose another.")
    
    return render_template("signup.html", form=form)

@views.route("/login", methods=["GET", "POST"])
def login():
    form = forms.LoginForm()
    if form.validate_on_submit():
        username = form.data["username"]
        user = users.get_user(username)

        if user is not None:
            password = form.data["password"]
            if passlib.hash.pbkdf2_sha256.verify(password, user.password):
                login_user(user)
                flash("Welcome to SpaceXhibit!")

                return redirect(url_for("views.home"))
            else:
                flash("Wrong password.")
        else:
            flash("You're not on the guest list. Why don't you sign up?")
    
    return render_template("login.html", form=form)

@views.route("/logout")
def logout():
    logout_user()
    return redirect(url_for("views.home"))

@views.route('/home')
@views.route("/")
def home():
    return render_template("home.html")

# Capsules
@views.route('/capsules', methods=['GET', 'POST'])
def capsules():
    capsule_data = database.get_capsules()
    return render_template("capsules.html", capsules=capsule_data)

@views.route("/add_capsule", methods=["POST"])
def add_capsule():
    database.add_capsule(request)
    return redirect(url_for("views.capsules"))

@views.route('/delete_capsule', methods=['GET'])
def delete_capsule():
    database.delete_capsule(request.args.get("capsule_id"))
    return redirect(url_for("views.capsules"))

@views.route('/update_capsule', methods=['POST'])
def update_capsule():
    database.update_capsule(request)
    return redirect(url_for("views.capsules"))

# Cores
@views.route('/cores', methods=['GET', 'POST'])
def cores():
    core_data = database.get_cores()
    return render_template("cores.html", cores=core_data, core_form = forms.CoresForm())
    
@views.route("/add_core", methods=["POST"])
@login_required
def add_core():
    if current_user.is_admin:
        database.add_core(request)
    return redirect(url_for("views.cores"))

@views.route('/delete_core', methods=['GET'])
@login_required
def delete_core():
    if current_user.is_admin:
        database.delete_core(request.args.get("core_id"))
    return redirect(url_for("views.cores"))

@views.route("/update_core", methods=["POST"])
@login_required
def update_core():
    if current_user.is_admin:
        database.update_core(request)
    return redirect(url_for("views.cores"))

@views.route('/filter_core', methods=['GET', 'POST'])
def filter_core():
    filter_core_data = database.filter_core(request)
    return render_template("cores.html", cores=filter_core_data, core_form = forms.CoresForm())

# Launches
@views.route('/launches', methods=['GET', 'POST'])
def launches():
    launch_data = database.get_launches()
    launch_details = database.get_launch_details()

    inexistent_launch_detail = []
    inexistent_launch_detail_dict = []

    rocket_data = database.get_rockets()
    rocket_dict = {}
    for rocket in rocket_data:
        rocket_dict[rocket["rocket_id"]] = rocket["name"].replace(" ", " ")
    
    launchpad_data = database.get_launchpads()
    launchpad_dict = {}
    for launchpad in launchpad_data:
        launchpad_dict[launchpad["launchpad_id"]] = launchpad["name"]

    ship_data = database.get_ships_only()
    ship_dict = {}
    for ship in ship_data:
        ship_dict[ship["ship_id"]] = ship["name"]
    
    capsule_data = database.get_capsules()
    capsule_dict = {}
    for capsule in capsule_data:
        capsule_dict[capsule["capsule_id"]] = capsule["serial"]

    present = False
    for launch in launch_data:
        for launch_detail in launch_details:
            if launch["launch_id"] == launch_detail["launch_id"]:
                present = True
                break
        if not present:
            inexistent_launch_detail += [launch["launch_id"]]
            inexistent_launch_detail_dict += [{"launch_id": launch["launch_id"], "name": launch["name"]}]
        present = False

    launch_data = database.get_launches()
    return render_template("launches.html", launches=launch_data, launch_details = launch_details,
    inexistent_launch_detail=inexistent_launch_detail,inexistent_launch_detail_dict=inexistent_launch_detail_dict,
    formM=forms.LaunchForm(), formD=forms.LaunchDetailForm(),
    rockets=rocket_dict, launchpads = launchpad_dict, ships = ship_dict, capsules = capsule_dict)

@views.route("/add_launch", methods=["POST"])
def add_launch():
    database.add_launch(request)
    return redirect(url_for("views.launches"))

@views.route('/add_launch_detail', methods=['POST'])
def add_launch_detail():
    database.add_launch_details(request)
    return redirect(url_for("views.launches"))

@views.route('/delete_launch', methods=['GET'])
def delete_launch():
    database.delete_launch(request.args.get("launch_id"))
    return redirect(url_for("views.launches"))

@views.route('/delete_launch_detail', methods=['GET'])
def delete_launch_detail():
    database.delete_launch_details(request.args.get("launch_id"))
    return redirect(url_for("views.launches"))

@views.route('/update_launch', methods=['POST'])
def update_launch():
    database.update_launch(request)
    return redirect(url_for("views.launches"))

@views.route('/update_launch_detail', methods=['POST'])
def update_launch_detail():
    database.update_launch_detail(request)
    return redirect(url_for("views.launches"))

@views.route('/launches_filtered', methods=['GET', 'POST'])
def launches_filtered():
    filter_data = database.filter_launches(request)
    return render_template("launches.html", launches=filter_data, formM=forms.LaunchForm())

# Launchpads
@views.route('/launchpads', methods=['GET'])
def launchpads():
    launchpad_data = database.get_launchpads()
    return render_template("launchpads.html", launchpads=launchpad_data)

# Payloads
@views.route('/payloads', methods=['GET'])
def payloads():
    payload_data = database.get_payloads()
    return render_template("payloads.html", payloads=payload_data, formM=forms.PayloadForm())

@views.route('/payloads_filtered', methods=['GET', 'POST'])
def payloads_filtered():
    filter_data = database.filter_payloads(request)
    return render_template("payloads.html", payloads=filter_data, formM=forms.PayloadForm())


@views.route('/add_payload', methods=['POST'])
@login_required
def add_payload():
    database.add_payload(request)
    return redirect(url_for("views.payloads" ))

@views.route("/update_payload", methods=["POST"])
def update_payload():
    database.update_payload(request)
    return redirect(url_for("views.payloads"))

@views.route('/delete_payload', methods=['GET'])
@login_required
def delete_payload():
    if current_user.is_admin:
        database.delete_payload(request.args.get("payload_id"))
    else:
        flash("Please do not poke around the exhibit.")
    return redirect(url_for("views.payloads"))

# Rockets
@views.route('/rockets', methods=['GET', 'POST'])
def rockets():
    rocket_data = database.get_rockets()
    rocket_d1_data = database.get_rocket_d1()
    rocket_d2_data = database.get_rocket_d2()
    rocket_image_data = database.get_rocket_image()

    inexistent_rocket_d1 = []
    inexistent_rocket_d2 = []
    inexistent_rocket_image = []
    inexistent_rocket_d1_dict = []
    inexistent_rocket_d2_dict = []
    inexistent_rocket_image_dict = []

    present = False
    for rocket in rocket_data:
        for rocket_d1 in rocket_d1_data:
            if rocket["rocket_id"] == rocket_d1["rocket_id"]:
                present = True
                break
        if not present:
            inexistent_rocket_d1 += [rocket["rocket_id"]]
            inexistent_rocket_d1_dict += [{"rocket_id": rocket["rocket_id"], "name": rocket["name"]}]
        present = False

        for rocket_d2 in rocket_d2_data:
            if rocket["rocket_id"] == rocket_d2["rocket_id"]:
                present = True
                break
        if not present:
            inexistent_rocket_d2 += [rocket["rocket_id"]]
            inexistent_rocket_d2_dict += [{"rocket_id": rocket["rocket_id"], "name": rocket["name"]}]
        present = False
        
        for rocket_image in rocket_image_data:
            if rocket["rocket_id"] == rocket_image["rocket_id"]:
                present = True
                break
        if not present:
            inexistent_rocket_image += [rocket["rocket_id"]]
            inexistent_rocket_image_dict += [{"rocket_id": rocket["rocket_id"], "name": rocket["name"]}]
        present = False

    return render_template("rockets.html", rockets=rocket_data,

website/templates/base.html
<!-- This is a base html file which means the other pages will inherit from it. It includes the essentials that are going to be
in every page such as a navigation bar -->

<!-- We will use Jinja Templating Language which allows us to write a little bit of python code in our html files. This reduces the
use of JavaScript -->

<!-- We will use Bootstrap5 for stylizing the page -->
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <!-- Links to include the path to Bootstrap5 in order to use the custom classes -->
    <!-- CSS only -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css" rel="stylesheet" 
      integrity="sha384-rbsA2VBKQhggwzxH7pPCaAqO46MgnOM80zW1RWuH61DGLwZJEdK2Kadq2F9CUG65" 
      crossorigin="anonymous">
    <link
      rel="stylesheet"
      href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css"
      crossorigin="anonymous"
    />
    <!-- JavaScript Bundle with Popper -->
    <script defer src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js" 
      integrity="sha384-kenU1KFdBIe4zVF0s0G1M5b4hcpxyD9F7jL+jjXkk+Q2h455rYXK/7HAuoJl+0I4" 
      crossorigin="anonymous"></script>
    <link rel="stylesheet" href="{{ url_for('static', filename='styles.css') }}">
    <title>{% block title %}Home{% endblock %}</title> <!-- This is the Jinja syntax -->
  </head>
  <body>
    <nav class="navbar navbar-expand-lg navbar-light bg-warning" style="padding-left: 10em">
      <button
        class="navbar-toggler"
        type="button"
        data-toggle="collapse"
        data-target="#navbar"
      >
        <span class="navbar-toggler-icon"></span>
      </button>
      <svg xmlns="http://www.w3.org/2000/svg" width="25" height="25" fill="currentColor" class="bi bi-rocket" viewBox="0 0 16 16">
        <path d="M8 8c.828 0 1.5-.895 1.5-2S8.828 4 8 4s-1.5.895-1.5 2S7.172 8 8 8Z"/>
        <path d="M11.953 8.81c-.195-3.388-.968-5.507-1.777-6.819C9.707 1.233 9.23.751 8.857.454a3.495 3.495 0 0 0-.463-.315A2.19 2.19 0 0 0 8.25.064.546.546 0 0 0 8 0a.549.549 0 0 0-.266.073 2.312 2.312 0 0 0-.142.08 3.67 3.67 0 0 0-.459.33c-.37.308-.844.803-1.31 1.57-.805 1.322-1.577 3.433-1.774 6.756l-1.497 1.826-.004.005A2.5 2.5 0 0 0 2 12.202V15.5a.5.5 0 0 0 .9.3l1.125-1.5c.166-.222.42-.4.752-.57.214-.108.414-.192.625-.281l.198-.084c.7.428 1.55.635 2.4.635.85 0 1.7-.207 2.4-.635.067.03.132.056.196.083.213.09.413.174.627.282.332.17.586.348.752.57l1.125 1.5a.5.5 0 0 0 .9-.3v-3.298a2.5 2.5 0 0 0-.548-1.562l-1.499-1.83ZM12 10.445v.055c0 .866-.284 1.585-.75 2.14.146.064.292.13.425.199.39.197.8.46 1.1.86L13 14v-1.798a1.5 1.5 0 0 0-.327-.935L12 10.445ZM4.75 12.64C4.284 12.085 4 11.366 4 10.5v-.054l-.673.82a1.5 1.5 0 0 0-.327.936V14l.225-.3c.3-.4.71-.664 1.1-.861.133-.068.279-.135.425-.199ZM8.009 1.073c.063.04.14.094.226.163.284.226.683.621 1.09 1.28C10.137 3.836 11 6.237 11 10.5c0 .858-.374 1.48-.943 1.893C9.517 12.786 8.781 13 8 13c-.781 0-1.517-.214-2.057-.607C5.373 11.979 5 11.358 5 10.5c0-4.182.86-6.586 1.677-7.928.409-.67.81-1.082 1.096-1.32.09-.076.17-.135.236-.18Z"/>
        <path d="M9.479 14.361c-.48.093-.98.139-1.479.139-.5 0-.999-.046-1.479-.139L7.6 15.8a.5.5 0 0 0 .8 0l1.079-1.439Z"/>
      </svg>
      <div class="collapse navbar-collapse" id="navbar">
        <div class="navbar-nav">
          <a class="nav-item nav-link" id="home" href="/home">Home</a>
          <a class="nav-item nav-link" id="launches" href="/launches">Launches</a>
          <a class="nav-item nav-link" id="launchpads" href="/launchpads">Launchpads</a>
          <a class="nav-item nav-link" id="rockets" href="/rockets">Rockets</a>
          <a class="nav-item nav-link" id="ships" href="/ships">Ships</a>
          <a class="nav-item nav-link" id="payloads" href="/payloads">Payloads</a>
          <a class="nav-item nav-link" id="cores" href="/cores">Cores</a>
          <a class="nav-item nav-link" id="capsules" href="/capsules">Capsules</a>

          {% if not current_user.is_authenticated %}
            <a class="nav-item nav-link pad-left" href="{{ url_for('views.login') }}">Login</a>
          {% else %}
            <p class="nav-item nav-link pad-left" style="margin: 0;">You are logged in as {{ current_user.username }}.</p>
            <a class="nav-item nav-link pad-left" href="{{ url_for('views.logout') }}">Logout</a>
          {% endif %}

        </div>
      </div>
    </nav>

    <div class = "container">
      {% block content %}
      {% endblock %}
    </div>

    {% for message in get_flashed_messages() %}
      <div id="liveToast" class="toast show" role="alert" aria-live="assertive" aria-atomic="true" style="position: fixed; right: 5em; bottom: 5em">
        <div class="toast-header">
          <strong class="me-auto">{{ message }}</strong>
          <button type="button" class="btn-close" data-bs-dismiss="toast" aria-label="Close"></button>
        </div>
      </div>
    {% endfor %}

    <!-- Make sure this javascript script is at the bottom of the body -->
    <script
      src="https://code.jquery.com/jquery-3.2.1.slim.min.js"
      integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN"
      crossorigin="anonymous"
    ></script>
    <script
      src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"
      integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q"
      crossorigin="anonymous"
   ></script>
    <script
      src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"
      integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl"
      crossorigin="anonymous"
    ></script>
    <script
      type="text/javascript"
      src="{{ url_for('static', filename='index.js') }}"
    ></script>
    <!-- Things written between two curly braces are python codes (Jinja feature) -->
  </body>
</html>

website/templates/capsules.html
{% extends "base.html" %} <!-- This file inherits base.html --> 
{% block title %}SpaceXhibit - Capsules{% endblock %} <!-- This is the Jinja syntax -->

{% block content %} <!-- This is the content block, whatever you include here will be visible on the screen -->
<br/>
<header>
    <h2> Capsules </h2>
    <p>
        These are the capsules that own by SpaceX Rockets.
    </p>
</header>

<table class = "table table-hover table-sm" style="text-align: center;">
    <thead>
        <tr class = "table-active">
            <th>Serial</th>
            <th>Status</th>
            <th>Reuse Count</th>
            <th>Water Landings</th>
            <th>Land Landings</th>
        </tr>
    </thead>
    <tbody>
        {% for capsule in capsules %}
    <tr class>
        <td>
            {{"-" if capsule["serial"] == None else capsule["serial"]}}
        </td>
        <td>
            {{"-" if capsule["status"] == None else capsule["status"]}}
        </td>
        <td>
            {{capsule["reuse_count"]}}
        </td>
        <td>
            {{capsule["water_landings"]}}
        </td>
        <td>
            {{capsule["land_landings"]}}
        </td>
    </tr>
    {% endfor %}
</table>

<!-- This endblock denotes the end of the content block, nothing should come after it-->
{% endblock %}

website/templates/cores.html
{% extends "base.html" %}
{% block title %}SpaceXhibit - Cores{% endblock %}

{% block content %} <!-- This is the content block, whatever you include here will be visible on the screen -->
<br/>
<header>
<h2> Cores </h2>
<p>
    These are the cores that are owned by SpaceX Rockets, you can search or browse the cores in our database!
    {% if not current_user.is_admin %} Please <a href="/login">login</a> update, delete or add core data. {% endif %}
</p>
<header>
            <button type="button" class="btn btn-warning btn" data-toggle="modal" data-target="#add-core-modal" style="position: fixed; bottom: 5em; right: 2.5em;">
                New Core
            </button>
            <button type="button" class="btn btn-warning" data-toggle="modal" data-target="#filter-core-modal" style="position: fixed; bottom: 2.5em; right: 2.5em;">
                Filter Core
            </button>
<table class = "table table-hover table-sm">
    <tr class = "table-active" style="text-align: center;">
        <th>Serial</th>
        <th>Status</th>
        <th>Reuse Count</th>
        <th>Block</th>
        <th>Real Time Locating System Attempts</th>
        <th>Real Time Locating System Landings</th>
        <th>Autonomous Spaceport Drone Ship Attempts</th>
        <th>Autonomous Spaceport Drone Ship Landings</th>
        <th colspan="2">Edit</th>
    </tr>
    {% for core in cores %}
    <tr class style="text-align: center;">
        <td>
            {{core["serial"]}}
        </td>
        <td>
            {{core["status"]}}
        </td>
        <td>
            {{core["reuse_count"]}}
        </td>
        <td>
            {{core["block"]}}
        </td>
        <td>
            {{core["rtls_attempts"]}}
        </td>
        <td>
            {{core["rtls_landings"]}}
        </td>
        <td>
            {{core["asds_attempts"]}}
        </td>
        <td>
            {{core["asds_landings"]}}
        </td>
        <td>
            <button type="button" class="btn btn-danger btn-sm" data-toggle="modal" onclick="delete_core('{{ core.core_id }}')">
                Delete
            </button>
        </td>
        <td>
            <button type="button" class="btn btn-warning btn-sm" data-toggle="modal" data-target="#update-core-modal-{{ core.core_id }}">
              Update
            </button>
        </td>
    </tr>
    {% endfor %}
</table>

<!-- Add new core -->
<div class="modal fade" id="add-core-modal" tabindex="-1" role="dialog" aria-labelledby="add-core-modal-label" aria-hidden="true">
    <div class="modal-dialog" role="document">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title" id="core-modal-label"> Add Core </h5>
        </div>
        <div class="modal-body"><form action="/add_core" method="POST" style="display: grid;">
          {{ core_form.csrf_token }}
          <div class="field">
              <label for="serial" class="form-label detail-field">Serial:</label>
              <div class="control detail-field">
                  {{ core_form.serial(class="form-control-sm")}}
              </div>
          </div>
          <div class="field">
              <label for="status" class="form-label detail-field">Status:</label>
              <div class="control detail-field">
                  {{ core_form.status(class="form-control-sm")}}
              </div>
          </div>
          <div class="field">
              <label for="reuse_count" class="form-label detail-field">Reuse Count:</label>
              <div class="control detail-field">
                  {{ core_form.reuse_count(class="form-control-sm")}}
              </div>
          </div>
          <div class="field">
            <label for="block" class="form-label detail-field">Block:</label>
            <div class="control detail-field">
                {{ core_form.block(class="form-control-sm")}}
            </div>
        </div>
          <div class="field">
              <label for="rtls_attempts" class="form-label detail-field">Real Time Locating System Attempts:</label>
              <div class="control detail-field">
                  {{ core_form.rtls_attempts(class="form-control-sm")}}
              </div>
          </div>
          <div class="field">
              <label for="rtls_landings" class="form-label detail-field">Real Time Locating System Landings:</label>
              <div class="control detail-field">
                  {{ core_form.rtls_landings(class="form-control-sm")}}
              </div>
          </div>
          <div class="field">
              <label for="asds_attempts" class="form-label detail-field">Autonomous Spaceport Drone Ship Attempts:</label>
              <div class="control detail-field">
                  {{ core_form.asds_attempts(class="form-control-sm")}}
              </div>
          </div>
          <div class="field">
              <label for="asds_landings" class="form-label detail-field">Autonomous Spaceport Drone Ship Landings:</label>
              <div class="control detail-field">
                  {{ core_form.asds_landings(class="form-control-sm")}}
              </div>
          </div>
  
          <button type=submit class="btn btn-warning">Add</button>
        </form>
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
        </div>
      </div>
    </div>
  </div>
  
 <!--Update table--> 
 {% for core in cores %}
    <div class="modal fade" id="update-core-modal-{{ core.core_id }}" tabindex="-1" role="dialog" aria-labelledby="update-core-modal-label-{{ core.core_id }}" aria-hidden="true">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="core-modal-label-{{ core.core_id }}"> Update {{ core.serial }} </h5>
                </div>
                <div class="modal-body"><form action="/update_core" method="POST" style="display: grid;">
                    {{ core_form.csrf_token }}
                    <div class="field" style="display: none">
                        <div class="control">
                            {{ core_form.core_id(value=core.core_id, class="form-control-sm")}}
                        </div>
                    </div>
                    <div class="field">
                        <label for="serial" class="form-label detail-field">Serial:</label>
                        <div class="control detail-field">
                            {{ core_form.serial(value=core.serial,class="form-control-sm")}}
                        </div>
                    </div>
                    <div class="field">
                        <label for="status" class="form-label detail-field">Status:</label>
                        <div class="control detail-field">
                            {{ core_form.status(value=core.status,class="form-control-sm")}}
                        </div>
                    </div>
                    <div class="field">
                        <label for="reuse_count" class="form-label detail-field">Reuse Count:</label>
                        <div class="control detail-field">
                            {{ core_form.reuse_count(value=core.reuse_count,class="form-control-sm")}}
                        </div>
                    </div>
                    <div class="field">
                        <label for="block" class="form-label detail-field">Block:</label>
                        <div class="control detail-field">
                            {{ core_form.block(value=core.block,class="form-control-sm")}}
                        </div>
                    </div>
                    <div class="field">
                        <label for="rtls_attempts" class="form-label detail-field">Real Time Locating System Attempts:</label>
                        <div class="control detail-field">
                            {{ core_form.rtls_attempts(value=core.rtls_attempts,class="form-control-sm")}}
                        </div>
                    </div>
                    <div class="field">
                        <label for="rtls_landings" class="form-label detail-field">Real Time Locating System Landings:</label>
                        <div class="control detail-field">
                            {{ core_form.rtls_landings(value=core.rtls_landings,class="form-control-sm")}}
                        </div>
                    </div>
                    <div class="field">
                        <label for="asds_attempts" class="form-label detail-field">Autonomous Spaceport Drone Ship Attempts:</label>
                        <div class="control detail-field">
                            {{ core_form.asds_attempts(value=core.asds_attempts,class="form-control-sm")}}
                        </div>
                    </div>
                    <div class="field">
                        <label for="asds_landings" class="form-label detail-field">Autonomous Spaceport Drone Ship Landings:</label>
                        <div class="control detail-field">
                            {{ core_form.asds_landings(value=core.asds_landings,class="form-control-sm")}}
                        </div>
                    </div>
                    <button type=submit class="btn btn-warning">Update</button>
                </form>
                </div>
                <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                </div>
            </div>
        </div>
    </div>
{% endfor %}


<!-- FILTER -->
<div class="modal fade" id="filter-core-modal" tabindex="-1" aria-labelledby="filter-core-modal-label" aria-hidden="true">
    <div class="modal-dialog modal-sm">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="filter-core-modal-label">Search</h5>
                <button type="button" class="btn-close" data-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body"><form action="/filter_core" method="POST">
                    <label for="fserial" class="form-label">Serial:</label>
                    <input type="text" class="form-control" name="fserial"> 

                    <label for="fstatus" class="form-label">Status:</label>
                    <input type="text" class="form-control" name="fstatus">

                    <label for="freuse_count" class="form-label">Reuse Count:</label>
                    <input type="integer" class="form-control" name="freuse_count">

                    <label for="fblock" class="form-label">Block:</label>
                    <input type="integer" class="form-control" name="fblock">
                    
                    <label for="frtls_attempts" class="form-label">Real Time Locating System Attempts:</label>
                    <input type="integer" class="form-control" name="frtls_attempts">

                    <label for="frtls_landings" class="form-label">Real Time Locating System Landings:</label>
                    <input type="integer" class="form-control" name="frtls_landings">

                    <label for="fasds_attempts" class="form-label">Autonomous Spaceport Drone Ship Attempts:</label>
                    <input type="integer" class="form-control" name="fasds_attempts">

                    <label for="fasds_landings" class="form-label">Autonomous Spaceport Drone Ship Landings:</label>
                    <input type="integer" class="form-control" name="fasds_landings">
                    
                    <div class="modal-footer">
                        <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                        <button type="submit" class = "btn btn-warning">Filter</button>
                    </div>
                </form>      
            </div>
        </div>
    </div>
</div>


{% endblock %}

website/templates/ship_details_1.html
{% extends "base.html" %} <!-- This file inherits base.html --> 
{% block title %}SpaceXhibit - Launchpads{% endblock %} <!-- This is the Jinja syntax -->

{% block content %} <!-- This is the content block, whatever you include here will be visible on the screen -->

<h1> This is the launchpads page, You can make queries and searches for specific launchpads</h1>



<!-- This endblock denotes the end of the content block, nothing should come after it-->
{% endblock %}